<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\ProdSight.Api.Modules\IdentityModule\Presentation\ProdSight.Api.Modules.IdentityModule.Presentation.csproj" />
    <ProjectReference Include="..\ProdSight.Api.Modules\MeasurementModule\Presentation\ProdSight.Api.Modules.MeasurementModule.Presentation.csproj" />
    <ProjectReference Include="..\ProdSight.Api.Shared\ProdSight.Api.Shared.csproj" />
    <ProjectReference Include="..\ProdSight.Api.Shared.DTOs\ProdSight.Api.Shared.DTOs.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="prometheus-net.AspNetCore" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>